language: node_js

node_js:
  - lts/*

postgres:
  adapter: postgresql
  database: yugi-collection-test
  username: postgres
  password: postgres
  
matrix:
  fast_finish: true
  
install:
  - npm i -g yarn
  - sudo apt-get install -yq
  - sudo service postgresql stop
  - sudo apt install -yq
  - sudo service postgresql start
  - npm i jest
  - yarn

services:
  - postgresql

script:
  - "yarn run test"

cache:
  directories:
    - node_modules

git:
  depth: 1