language: node_js

node_js:
  - lts/*

matrix:
  fast_finish: true

install:
  - npm i -g yarn
  - npm i jest
  - yarn

script:
  - "yarn run test"

cache:
  directories:
    - node_modules

git:
  depth: 1