language: node_js

node_js:
  - lts/*

matrix:
  fast_finish: true

install:
  - npm uninstall typescript --no-save
  - npm install

script:
  - "npm run test"

cache:
  directories:
    - node_modules

git:
  depth: 1