version: "3"
services: 
  redis:
    image: redis
  db:
    image: postgres
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yugi-collection
    ports: 
      - "5432:5432"
  
  server:
    image: sirawichDev/yugi:lastest
    ports: 
      - "4000:4000"
    depends_on: 
      - db
      - redis